apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: redis-master
        tier: backend
    spec:
      containers:
      - name: redis-master-container
        image: k8s.gcr.io/redis:e2e
        ports:
        - containerPort: 6379
